name: Image Builder

on:
  push:
  workflow_dispatch:

jobs:
  PHP:
    strategy:
      matrix:
        build: [
          "7.4", "8.1"
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"
      - name: Enable experimental features for the Docker daemon and CLI
        run: |
          echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'
          docker buildx version
      - name: Setup docker-slim
        run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
      - name: Setup docker-squash
        run: pip install --user https://github.com/goldmann/docker-squash/archive/master.zip
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker
        run : |
          docker build -f php/${{ matrix.build }}/Dockerfile -t jpratama7/php-fpm-nginx:build-fat .
          docker-squash -v -t jpratama7/php-fpm-nginx:${{ matrix.build }}-latest jpratama7/php-fpm-nginx:build-fat
          docker push jpratama7/php-fpm-nginx:${{ matrix.build }}-latest
          docker-squash -v -t jpratama7/php-fpm-nginx:${{ matrix.build }} jpratama7/php-fpm-nginx:build-fat
          docker push jpratama7/php-fpm-nginx:${{ matrix.build }}

  Python:
    strategy:
      matrix:
        build: [
          "3.10"
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.build }}
      - name: Enable experimental features for the Docker daemon and CLI
        run: |
          echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'
          docker buildx version
      - name: Setup docker-slim
        run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
      - name: Setup docker-squash
        run: pip install --user https://github.com/goldmann/docker-squash/archive/master.zip
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker
        run : |
          docker build -f python/${{ matrix.build }}/Dockerfile -t jpratama7/bullseye-python:build-fat-${{ matrix.build }} .
          docker-squash -v -t jpratama7/bullseye-python:latest-${{ matrix.build }} jpratama7/bullseye-python:build-fat-${{ matrix.build }}
          docker-squash -v -t jpratama7/bullseye-python:${{ steps.date.outputs.date }}-${{ matrix.build }} jpratama7/bullseye-python:build-fat-${{ matrix.build }}
          docker push jpratama7/bullseye-python:${{ steps.date.outputs.date }}-${{ matrix.build }}
          docker push jpratama7/bullseye-python:latest-${{ matrix.build }}